:page-layout: post
:page-title: Fault Tolerance 6.0.0
:page-synopsis: SmallRye Fault Tolerance 6.0.0 released!
:page-tags: [announcement, microprofile]
:page-date: 2022-09-07 15:00:00.000 +0100
:page-author: lthon
:smallrye-ft: SmallRye Fault Tolerance
:microprofile-ft: MicroProfile Fault Tolerance

= Fault Tolerance 6.0.0

Today, we announce the https://github.com/smallrye/smallrye-fault-tolerance/releases/tag/6.0.0[release] of {smallrye-ft} 6.0.0.

This release implements {microprofile-ft} 4.0 and therefore supports Jakarta EE 9 / MicroProfile 5.0.
Implementation-wise, the 6.0.0 release corresponds to link:/blog/fault-tolerance-5-5/[{smallrye-ft} 5.5.0].
Additionally, {smallrye-ft} 6.0.0 requires Java 11 at minimum; it is no longer compatible with Java 8.

For the time being, we will produce releases both in the 5.x and 6.x streams.
There will always be a direct correspondence between a 5.x and a 6.x release:

[cols="1,1",options="header"]
|===
|5.x release
|Corresponding 6.x release

|5.4.0
|6.0.0-RC2

|5.4.1
|6.0.0-RC3

|5.5.0
|6.0.0-RC4

|5.5.0
|6.0.0

|5.5.1 (hypothetically)
|6.0.1 (hypothetically)

|5.6.0 (hypothetically)
|6.1.0 (hypothetically)

|5.6.1 (hypothetically)
|6.1.1 (hypothetically)

|5.7.0 (hypothetically)
|6.2.0 (hypothetically)
|===

At some point, we'll stop producing releases in the 5.x stream.
Shortly after that, we'll upgrade the basic dependencies (Jakarta CDI etc.) to their Jakarta EE 10 versions.
Since Jakarta EE 9 is mostly a transition release and runtimes we're aware of target Jakarta EE 10 anyway, we likely won't bump a major version for that.
In other words, the upgrade to Jakarta EE 10 base will happen in the 6.x stream and will not require a 7.0 release.

As usual, if you have any problems or ideas, including objections to the plan stated above, please https://github.com/smallrye/smallrye-fault-tolerance/issues[file an issue]!
