:page-layout: post
:page-title: Jandex 3.4.0
:page-synopsis: Jandex 3.4.0 released!
:page-tags: [announcement]
:page-date: 2025-07-21 09:00:00.000 +0100
:page-author: lthon

= Jandex 3.4.0

Today, we announce the https://github.com/smallrye/jandex/releases/tag/3.4.0[release] of Jandex 3.4.0.
This release contains one bugfix and one new feature.

Type annotations were not parsed correctly in certain situations involving nested types.
This bug is fixed in this release.

Jandex now also includes integration with Gizmo 2.
Gizmo 2 is an evolution of Gizmo, the bytecode generation framework used in Quarkus.
Gizmo version 1 used Jandex in its core, but Gizmo version 2 does not.
Therefore, an integration package is needed.
This version of Jandex includes one, providing all the necessary methods like `classDescOf(org.jboss.jandex.Type)` or `genericTypeOf(org.jboss.jandex.Type)`.
All integration code is present in `static` methods of the class `Jandex2Gizmo`.

If you experience any troubles, or if you have any ideas for Jandex improvements, please https://github.com/smallrye/jandex/issues[file an issue].
