:page-layout: post
:page-title: Jandex 3.4.0
:page-synopsis: Jandex 3.4.0 released!
:page-tags: [announcement]
:page-date: 2025-07-21 09:00:00.000 +0100
:page-author: lthon

= Jandex 3.4.0

Today, we announce the https://github.com/smallrye/jandex/releases/tag/3.4.0[release] of Jandex 3.4.0.
This release contains one bugfix and one new feature.

Type annotations were not parsed correctly in certain situations involving nested types.
This bug is fixed in this release.

Jandex now also includes integration with Gizmo 2.
Gizmo 2 is an evolution of Gizmo, the bytecode generation framework used in Quarkus.
Gizmo version 1 used Jandex in its core, but Gizmo version 2 does not.
Therefore, an integration package is needed.
This version of Jandex includes a new module, `io.smallrye:jandex-gizmo2`, which contains a class called `Jandex2Gizmo` with these `static` methods:

* `classDescOf()` to create `java.lang.constant.ClassDesc`
* `fieldDescOf()` to create `io.quarkus.gizmo2.desc.FieldDesc`
* `methodDescOf()` to create `io.quarkus.gizmo2.desc.MethodDesc`
* `constructorDescOf()` to create `io.quarkus.gizmo2.desc.ConstructorDesc`
* `genericTypeOf*()` to create `io.quarkus.gizmo2.GenericType` and its subtypes
* `typeArgumentOf()` to create `io.quarkus.gizmo2.TypeArgument`
* `copyTypeParameters()` and `addTypeParameter()`
* `copyAnnotations()` and `addAnnotation()`

If you experience any troubles, or if you have any ideas for Jandex improvements, please https://github.com/smallrye/jandex/issues[file an issue].
