:page-layout: post
:page-title: Fault Tolerance 6.11.0
:page-synopsis: SmallRye Fault Tolerance 6.11.0 released!
:page-tags: [announcement, microprofile]
:page-date: 2026-03-16 15:00:00.000 +0100
:page-author: lthon
:smallrye-ft: SmallRye Fault Tolerance
:microprofile-ft: MicroProfile Fault Tolerance

= Fault Tolerance 6.11.0

Today, we announce the https://github.com/smallrye/smallrye-fault-tolerance/releases/tag/6.11.0[release] of {smallrye-ft} 6.11.0.
This release contains one small improvement.

Previous versions of {smallrye-ft} did not support Java modularity (JPMS) at all.
With this version, automatic module names are provided for all useful modules.
The test suite modules do not have automatic module names, because they are never supposed to be used publicly.
The OpenTracing Context Propagation module is obsolete and should not be used these days, so it does not have an automatic module name either.
(Among other deprecated things, it will be removed in {smallrye-ft} 7.0.)

Note that to improve internal consistency and make sure that the module name is the same as a top-level package name of all classes in the module, a small number of internal classes were moved in this release.
Advanced integrators (such as Quarkus) need to take care, but this should be an invisible change for users.

We intend to provide full module descriptors in the future, but cannot do that at the moment.
This is because certain dependencies, notably the {microprofile-ft} API JAR, do not provide either automatic module names or module descriptors.

As usual, if you have any ideas for improvements, please https://github.com/smallrye/smallrye-fault-tolerance/issues[file an issue]!
