= SmallRye Committer Nomination Guide
:page-layout: community

Contributing to open source projects can be a lot of fun,
but it's even better when that project acknowledges your effort and makes you a committer as well!

This document outlines the process by which existing project committers can nominate external contributors to become a committer.

== Nomination Process

Upon recognizing that an external contributor has beneficially contributed to a particular SmallRye project,
over an extended period, existing committers of a SmallRye project can follow this process to nominate them:

* Post to the https://groups.google.com/d/forum/smallrye[Google Group] with the subject *[VOTE] xxx for SmallRye xxx committer*.
An example subject is *[VOTE] John Smith for SmallRye Reactive Messaging committer*.
The posting should detail:
** The person being nominated, including a link to their GitHub profile
** Brief reason on why they're being nominated
** Links to some contributions they've made to the project
* Anyone can comment on the posting. However, only existing SmallRye committers, from any project, will have a binding vote
* After 7 days the vote will end and the result will be posted in the https://groups.google.com/d/forum/smallrye[Google Group]
** A positive result is determined by Consensus Approval, i.e. at least 3 +1 votes and no -1 vote.
** Any -1 vote must include the reasoning, and the committer should be prepared to defend their vote.


Once the vote is complete, the nominee will be asked if they accept the nomination,
after which they will be notified when committer access has been granted to the particular SmallRye project.
