= SmallRye Committer Nomination Guide
:page-layout: community

Contributing to open source projects can be a lot of fun,
but it's even better when that project acknowledges your effort and makes you a committer as well!

This document outlines the process by which existing project committers can nominate external contributors to become a committer.

== Nomination Process

Upon recognizing that an external contributor has beneficially contributed to a SmallRye project,
over an extended period, they can follow this process to nominate them:

* Create a GitHub issue in the particular SmallRye project detailing:
** The person being nominated, including a link to their GitHub profile
** Brief reason on why they're being nominated
** Links to some contributions they've made to the project
* Add the *Nomination* label to the GitHub issue
* Post to the https://groups.google.com/d/forum/smallrye[Google Group] with the subject *Nominating xxx for SmallRye xxx*,
including a link to the issue
* The nomination will be posted to Twitter
* Anyone can comment on the nomination issue. However, only existing committers will have a binding vote
* After 10 days the vote will end and the result will be posted in the https://groups.google.com/d/forum/smallrye[Google Group]


Once the vote is complete, the nominee will be notified when committer access has been granted to the SmallRye project.
